### PR TITLE
Added Red-Black Trees implementation in Java

### PR DESCRIPTION
**Pull request by AjayThorve**
Added Red-Black Trees java code, let me know if it needs any changes

### CODE REVIEW

**Comment by xuzebin** [comment]
Thanks for your contribution. We are following Google's Java style guide.
Before merging, please:

- Remove .class files.
- Follow the naming conventions in https://google.github.io/styleguide/javaguide.html#s5-naming.

Thank you

**Comment by AjayThorve** [comment]
Edited the files as requested...kindly review

**Comment by xuzebin** [comment]
Ajay, the class name "node" should be "Node". Class names are written in UpperCamelCase.

**Comment by AjayThorve** [comment]
Changed the class name format to UpperCamelCase.

**Comment by xuzebin** [comment]
Did you test by running your code?

**Comment by AjayThorve** [comment]
Yes...just now tested it again...resolved a few bugs which were created during changing naming conventions..can confirm its working now

**Pull request merged**
