### PR TITLE
Java implementation of maximum subarray

### PR DESCRIPTION
**Pull request by xuzebin**
Professor Callahan, I have implemented the maximum subarray problem in Java following the textbook and made some tiny modifications to the previous binary search tree implementation.

### CODE REVIEW

**Comment by gcallah** [comment]
I cleaned up the indentation a bit. Please make sure to refresh your fork before working again.

**Comment by gcallah** [comment]
Oops, I'm trying a new method of handling pull requests, and it didn't seem to handle your binary search tree material properly: can you re-issue the pull request?

**Comment by gcallah** [comment]
Oops, my comment re-opened it: never mind!

**Comment by gcallah** [comment]
I don't think I got this merged properly. I cleaned up DivideConquer.java, but I seem to have lost the binary search changes. My apologies.

**Comment by xuzebin** [comment]
Prof. Callahan,
1. The indentation of the original DivdeAndConquer should look fine on Github.
2. The BST is correct with no lost changes.

**Comment by gcallah** [comment]
I am not concerned only with how it looks on GitHub: it should look good in vim as well!

Always best to use spaces rather than tabs.

Let’s look at this together next Monday.

**Pull request merged**
