### PR TITLE
Heapsort & RandomizedAlgorithms & Renaming (Java)

### PR DESCRIPTION
**Pull request by xuzebin**
- Both min/max heap and min/max priority queue are implemented.
- Randomized Algorithms for Hiring Problem.
- Rename some directories.

TODO:
- Add unit tests.

### CODE REVIEW

**Comment by nandukalidindi** [comment]
👍 Awesome code organisation. I think you can directly create a branch out of this repository and then issue a pull request rather than having to issue one from your forked repository.

**Comment by xuzebin** [comment]
Nandu,
Yes, you are right. I'll do that later.

**Comment by xuzebin** [comment]
@prashant182 I think I should merge now since I've changed the name of directories under Java so you'd better pull before committing your sorting code tonight.

**Comment by prashant182** [comment]
Ok

On Jan 30, 2017 10:47 PM, "Zebin Xu" <notifications@github.com> wrote:

@prashant182 <https://github.com/prashant182> I think I should merge now
since I've changed the name of directories under Java so you'd better pull
before committing your sorting code tonight.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gcallah/algorithms/pull/43#issuecomment-276268016>, or mute
the thread

**Pull request merged**
