### PR TITLE
Fixed the bug which was not allowing the edges to be rendered 

### PR DESCRIPTION
**Pull request by vc1202**
Remaining:
a)Adding a Delay
b)Highlight functionality

Professor, Please review this

### CODE REVIEW

**Comment by gcallah** [comment]
Hi Varun, we have conflicts to resolve to merge this branch: I think because I renamed files to bring Vainika in to the system. Can you save your work in a temp directory, fetch the new files with a pull, and then put your new work back in the new files? Talk to me if confused.

**Comment by vc1202** [comment]
Sure Prof, I will do this first thing in the morning.
Also for a status update: I also coded the delay part so that drawing is going slow.

Best,
Varun chopra

**Comment by gcallah** [comment]
Very good... let's meet soon.

**Comment by vc1202** [comment]
Hi Professor, I don't know if I was able to successfully resolve conflicts. Please check and let me know Asap.

**Comment by nandukalidindi** [comment]
@vc1202 There is a file change of 642 files which is huge and this PR seems to have removed many files like `.gitignore`, `.travis.yml`. From the conversation I can see that the merge with master was not successful.

**Pull request merged**
